#This script smmarizes geomorphic assemblages by reach

#Natalie Kramer (n.kramer.anderson@gmail.com)
#Last Updated July 13 2019

#Documentation available on 
#https://natalie-kramer.github.io/GeomorphicUpscale/


# Dependencies ------------------------------------------------------------

library(tidyverse)

source(file.path(repo.dir, "scripts\\plot.colors.R"))
source(file.path(repo.dir, "scripts\\functions.R"))


# user variables defined in UpscaleWrapper.R ------------------------------------------------------------
proj.dir = proj.dir  # directory path to local project
repo.dir = repo.dir   # directory path to Github repo
selections = selections # directory path to input selections file generated by RSselection.R
gu.type = gu.type      # Options: UnitForm, GU
RSlevels = RSlevels # optional vector argument to set RS factor order in graphs and displays, leave as  NA if alphabetical is desired

# set directories  ------------------------------------------------------------------------

# set assemblage output directory
assemblage.dir = file.path(proj.dir, "Outputs/Assemblage", gu.type, "Reach")
if(!file.exists(assemblage.dir)){dir.create(assemblage.dir, recursive = TRUE)}

# delete any existing files in Output from previous runs
unlink(file.path(assemblage.dir, "*"), recursive = TRUE)

# set path to repo gut metric tables
metrics.dir = file.path(repo.dir, "Database/Metrics")

# specify gut output layer and corresponding metric table to draw data from based on gu.type parameter
if(gu.type == "GU"){
  layer = "Tier3_InChannel_GU" 
  gut.metrics = "Site_GUTMetrics_Tier3_InChannel_GU.csv"}
if(gu.type == "UnitForm" | gu.type == "UnitShape"){
  layer = "Tier2_InChannel"
  gut.metrics = "Site_GUTMetrics_Tier2_InChannel.csv"}

# Read in data and summarize ----------------------------------------------

# read in site data and convert to long data format
# add wet to bankfull area ratio
site.metrics = read_csv(file.path(metrics.dir, gut.metrics)) %>%
  select(-gut.layer) %>%
  mutate(wet.bf.area.ratio = round(wet.area.m2 / bf.area.m2, 3)) %>%
  gather(value = "value", key = "variable", -visit.id)

# join site metrics and selections
# add unit.type (here all units) and ROI 
site.data = selections %>% 
  select(RS, Condition, visit.id) %>%
  inner_join(site.metrics, by = 'visit.id') %>%
  mutate(unit.type = "all", ROI = "bankfull")

# re-set ROI to wettedf for rows where variable is 'wet.area.m2'
site.data = site.data %>%
  mutate(ROI = ifelse(variable == 'wet.area.m2', 'wetted', ROI))

print("making summary tables and plots...")

#summarize data pooling in different ways and write to files

make.outputs(site.data, pool.by = "RSCond", out.dir = assemblage.dir, RSlevels = RSlevels)
make.outputs(site.data, pool.by = "RS", out.dir = assemblage.dir, RSlevels = RSlevels)
make.outputs(site.data, pool.by = "All", out.dir = assemblage.dir, RSlevels = RSlevels)

# # cleaning up ----------------------------------------------
# 
# print("erasing temporary variables")
# 
# keepvars=c("proj.dir","repo.dir", "selections",
#            "plot.type", "my.scales" , "RSlevels", "gu.type")
#   rm(list=ls()[-match(x = keepvars, table = ls())])
#   
# print("done")
#   
  
