
#This script takes the OUtput from GUT and summarizes responses by Unit


# To Do -------------------------------------------------------------------

# Nk todo
#eliminate species and model from directory structure and instead include as field in output table?  Maybe append to this table
#when run for different species or just run for all species and model types on the fly-- not make a user variable...?

# Dependencies ------------------------------------------------------------

require(tidyverse)

source(file.path(repo.dir, "scripts\\plot.colors.R"))
source(file.path(repo.dir, "scripts\\functions.R"))


# user variables defined in UpscaleWrapper.R ------------------------------------------------------------

proj.dir = proj.dir  # directory path to local project
repo.dir = repo.dir   # directory path to Github repo
selections = selections # directory path to input selections file generated by RSselection.R
gu.type = gu.type      # Options: UnitForm, GU #UnitShape not available at this time since I don't have maps of these in the database
RSlevels = RSlevels # optional vector argument to set RS factor order in graphs and displays, leave as  NA if alphabetical is desired
in.species = species   #Options: steelhead, chinook
in.model = model    ##Options: nrei, fuzzy
in.lifestage = lifestage  ##Options: spawner, juvenile


# set directories and paths ------------------------------------------------------------------------

# set respons output directory
# note: str_to_sentence will convert first letter of species and lifestage to upper case
response.dir = file.path(proj.dir, "Outputs/Response", str_to_sentence(in.species), str_to_sentence(in.lifestage), "Unit", gu.type)
if(!file.exists(response.dir)){dir.create(response.dir, recursive = TRUE)}

# delete any existing files in output directory from previous runs
unlink(file.path(response.dir, "*"), recursive = TRUE)

# set path to repo gut metric tables
metrics.dir = file.path(repo.dir, "Database/Metrics")

# specify gut output layer and corresponding metric table to draw data from based on gu.type parameter
if(gu.type == "GU"){
  layer = "Tier3_InChannel_GU" 
  gut.metrics = "Unit_Fish_Metrics_Tier3_InChannel_GU.csv"}
if(gu.type == "UnitForm" | gu.type == "UnitShape"){
  layer = "Tier2_InChannel"
  gut.metrics = "Unit_Fish_Metrics_Tier2_InChannel.csv"}


# Reads in unit fish metric data ----------------------------------------------------

# read in unit metric fish data
unit.fish.metrics = read_csv(file.path(metrics.dir, gut.metrics))

# filter unit level resonse to model, species and lifestage specified
unit.fish = unit.fish.metrics %>% 
  filter(model == in.model & species == in.species & lifestage == in.lifestage)

# add field for ratio of suitable habitat area to hydro model area
# subset columns for plotting (note - dropping pred.fish.suitable bc exact same value as pred.fish)
unit.fish = unit.fish %>%
  mutate(suitable.area.ratio = round(hab.area.suitable / area.delft, 3)) %>%
  rename(unit.type = gu.type) %>%
  select(-pred.fish.suitable, -area.delft, - hab.area.suitable) # same as pred.fish so dropping


# convert to long form tibble 
unit.fish.long = unit.fish %>%
  gather(key = "variable", value = "value", -visit.id, -unit.type, -model, -species, -lifestage)

# join to selections
# remove rows where 'value' is na (these are visits where model was not run)
unit.response = selections %>% 
  select(RS, Condition, visit.id) %>%
  inner_join(unit.fish.long, by = 'visit.id') %>%
  filter(!is.na(value)) %>%
  mutate(ROI = "hydro",
         variable = factor(variable, levels = c('pred.fish', 'suitable.area.ratio', 'med', 'mean', 'sd', 'med.suitable', 'mean.suitable', 'sd.suitable'))) 

# summarizes data for use in upscale ----------------------------------------------------

make.outputs.unit(in.data = unit.response, pool.by = "RSCond", gu.type = gu.type, out.dir = response.dir, RSlevels = RSlevels)
make.outputs.unit(in.data = unit.response, pool.by = "RS", gu.type = gu.type, out.dir = response.dir, RSlevels = RSlevels)
make.outputs.unit(in.data = unit.response, pool.by = "All", gu.type = gu.type, out.dir = response.dir, RSlevels = RSlevels)
