#Summarizes geoindicators by RS selctions from database
#reach selections from RSselection.R. 

#Natalie Kramer (n.kramer.anderson@gmail.com)
#Last Updated July 13 2019

#Documentation available on 
#https://natalie-kramer.github.io/GeomorphicUpscale/


# To Do -------------------------------------------------------------------

# fix natalie's column dependent selection on line 43
#make pool by RS and Condition separate output folders  

# Dependencies -------------------------------------------------------------------

library(tidyverse)

source(file.path(repo.dir, "scripts\\plot.colors.R"))
source(file.path(repo.dir, "scripts\\functions.R"))

proj.dir = proj.dir  #directory path to local project
repo.dir = repo.dir   #directory path to Github repo
selections = selections #directory path to input selections file generated by RSselection.R
RSlevels = RSlevels #optional vector argument to set RS factor order in graphs and displays, leave as  NA if alphabetical is desired
my.scales = "free" #Options: fixed or free x/y axis scales for tiled plot output

# set up data refs and output file structure  ------------------------------------------------------------------------

# set and create geoindicator output directory
geo.dir = file.path(proj.dir, "Outputs/Selections/Geoindicators")
if(!file.exists(geo.dir)){dir.create(geo.dir, recursive = TRUE)}

#delete any existing files in Output from previous runs
unlink(paste(geo.dir,"\\*", sep=""), recursive = TRUE)

#Specify location of input metric tables
metrics.dir = paste(repo.dir,"\\Database\\Metrics" , sep="")

#create long format for selections of quatitative data
geoindicators = selections %>% 
  select(RS, Condition, visit.id, Gradient:Sndf) %>%
  gather(value = "value", key = "variable", -RS, -Condition, -visit.id) %>%
  mutate(unit.type = NA, ROI = "NA")



# making summaries  ------------------------------------------------------------------------

print("making summary outputs...")

# #summarized by All
# make.outputs(geoindicators, pool.by = "All", out.dir = geo.dir, RSlevels = RSlevels)
# 
# #summarized by River Style (RS)
# make.outputs(geoindicators, pool.by = "RS", out.dir = geo.dir, RSlevels = RSlevels)

#summarized by RS and Condition
make.outputs(geoindicators, pool.by = "RSCond", out.dir = geo.dir, RSlevels = RSlevels)


print(paste("Files written to:", geo.dir , sep= " "))

# # cleaning up ------------------------------------------------------------------------
# 
# 
# print("done. erasing temporary variables")
# 
# keepvars=c("proj.dir","repo.dir", "selections", 
#            "plot.type", "my.scales" , "RSlevels", "gu.type")
# rm(list=ls()[-match(x = keepvars, table = ls())])


